baseURL = "https://stockholm.serverlessdays.io/"
languageCode = "en-us"
title = "ServerlessDays Stockholm"

[params]
    logo = "/images/Logo1.png"
    description = "A community based conference focusing on Serverless based platforms and technologies. Stockholm, October 24, 2019"
    mascot = "/images/Anteater_mascot.png"
    date = "24 October 2019"
    city = "Stockholm"
    twitter = "ServerlessSthlm"
    email = "stockholm@serverlessdays.io"
    backgroundImage = "/images/Sthlm_2.JPG"
    prospectus = "/Prospectus_ServerlessDays_Stockholm_2019.pdf"
    ticketDate = "7 June 2019"
    ticketSaleUrl = "https://serverlessdays-stockholm-2019.eventbrite.com"
    cfpDate = "26 May 2019"
    cfpEndDate = "1 September 2019"
    cfpUrl = "https://www.papercall.io/serverlessdaysstockholm2019"
    emailForm = "https://forms.gle/ExTEhCahRuJYKv1d6"

[[params.dates]]
    date = "26 May 2019"
    text = "CFP Opens"
    done = true

[[params.dates]]
    date = "7 June 2019"
    text = "Tickets go on sale"
    done = false

[[params.dates]]
    date = "1 September 2019"
    text = "CFP closes"
    done = false

[[params.dates]]
    date = "7 September 2019"
    text = "Schedule announced"
    done = false    

[params.venue]
    name = "Openlab"
    link = "http://openlabsthlm.se"
    map = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2034.2063296591784!2d18.070274216072924!3d59.34620358166473!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x465f9d4034155555%3A0x67d41ef95a94b107!2sOpenlabs+Co-Working+Space!5e0!3m2!1ssv!2sse!4v1555256907911!5m2!1ssv!2sse"
    text = "Openlab’s Conference Center is centrally located in the KTH building right in front of the subway exit Tekniska Högskolan, Valhallavägen 79."

